# ansible-playbook -b --private-key ~/.ssh/id_rsa_multipass --ask-vault-pass vsr_vm_infra.yml

# on MacOS host
# ansible-galaxy install mrlesmithjr.netplan for netplan
# sudo pip3 install passlib (required on MacOS for encrypted passwords)
# ansible-vault create password.yml -> add password in plain text

---
- hosts: packet

  vars:
    src_license_path: "/Users/giancarlo3g/Downloads/VSR-SIM_R20_license.txt"
    src_xml_path: "/Users/giancarlo3g/Desktop/vsr01-sr1.xml"
    src_image_path: "/Users/giancarlo3g/Downloads/vm/sros-i386/sros-vm.qcow2"

  # create br-mgmt and br-wan bridges for Ubuntu 18.0 with netplan
  roles:
    - role: mrlesmithjr.netplan
      become: yes
      netplan_remove_existing: no
      netplan_config_file: /etc/netplan/my_netplan.yaml
      netplan_renderer: networkd 
      netplan_configuration:
        network:
          version: 2
          bridges:
            br-mgmt:
              addresses:
                - 192.168.1.1/24 
            br-wan:
              dhcp4: yes
      netplan_apply: True

  tasks:
    - name: install vsftpd for FTP server
      apt: 
        name: ['vsftpd']
        update_cache: yes
      become: yes

    - name: create admin user with passwd
      user:
        name: admin
        home: /home/admin
        password: "{{ 'admin' | password_hash('sha512') }}" # check vault file for plain text password
        update_password: always

    - name: create license directory
      file:
        path: /home/admin/license
        state: directory
        owner: admin

    - name: copy license to server
      copy:
        src: "{{ src_license_path }}"
        dest: /home/admin/license/VSR-SIM_R20_license.txt
      register: copy_status

    - name: create lab directory for config files
      file:
        path: /home/admin/lab
        state: directory
        owner: admin














