# ansible-playbook -b --private-key /Users/giancarlo3g/.ssh/id_rsa_multipass --ask-vault-pass vsr_vm.yml

# sudo pip install passlib is required on MacOS for encrypted passwords
# ansible-galaxy install mrlesmithjr.netplan for netplan
# ansible-vault create password.yml -> add password in plain text

---
- hosts: packet

  vars:
  tasks:
    - name: install basic pack
      apt: 
        name: ['qemu-kvm', 'libvirt-bin', 'vsftpd']
        update_cache: yes
      become: yes

    - name: create admin user with passwd
      user:
        name: admin
        home: /home/admin
        password: "{{ 'admin' | password_hash('sha512') }}" # check vault file for plain text password
        update_password: always

  # create br-mgmt and br-wan bridges
  roles:
    - role: mrlesmithjr.netplan
      become: yes
      netplan_enabled: true
      netplan_config_file: /etc/netplan/my-netplan.yaml
      netplan_renderer: networkd 
      netplan_configuration:
        network:
          version: 2
          bridges:
            br-mgmt:
              addresses:
                - 192.168.1.1/24 
              gateway4: 192.168.1.1
            br-wan:
              dhcp4: yes
      netplan_apply: True


#    - name: copy files to server



